#!/usr/bin/env python
"""Write the site's copies of the Tradecraft demo from the same sources build-demo.py uses.

Outputs (all GENERATED; edit the sources, not these):

    website/static/tech/tradecraft/tradecraft.js    web/ui.js, verbatim
    website/static/tech/tradecraft/tradecraft.css   web/demo.css + web/site/crosstab.css
    website/layouts/tech/tradecraft.html            the <main> of web/demo.template.html inside
                                                    the tech-kit chrome, then {{ .Content }},
                                                    then web/site/crosstab.partial.html

WHY (GitLab issue #5, and what the fix broke)
--------------------------------------------
`content/tech/tradecraft.md` declared `layout: tradecraft` and promised the cue floor "runs
above, in your browser" with no layout to render it. The 2026-09-06 fix split web/demo.html
into layout + css + js -- and in doing so dropped the "Method, not ideology -- checked"
cross-tab and the Rosetta cross-reference that the hand-written layout had carried, leaving
`crosstab.json` (gated by `crosstab-export`) consumed by nothing. The site-only pieces now
live under web/site/ as splitter inputs, so the page cannot lose them by being regenerated.

The JS is web/ui.js byte-for-byte. It grades nothing: the layout loads
/tech/instrument/engine.js first and ui.js calls window.Instrument, so the site page, the
standalone demo and /tech/instrument/ all run one engine over one payload.
`tools/test_engine_parity.py` asserts this file's outputs.

    python web/split_for_site.py           # write the three files
    python web/build-demo.py --check       # verify all generated files (includes these)
"""
from __future__ import annotations

import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                      # tradecraft/
SERIES = os.path.dirname(ROOT)                    # series-workspace/
WEB = os.path.join(SERIES, "website")
STATIC = os.path.join(WEB, "static", "tech", "tradecraft")
LAYOUT = os.path.join(WEB, "layouts", "tech", "tradecraft.html")

TEMPLATE = os.path.join(HERE, "demo.template.html")
CSS = os.path.join(HERE, "demo.css")
UI = os.path.join(HERE, "ui.js")
SITE_CSS = os.path.join(HERE, "site", "crosstab.css")
SITE_PARTIAL = os.path.join(HERE, "site", "crosstab.partial.html")

GENERATED = ("<!-- GENERATED by tradecraft/web/split_for_site.py from web/demo.template.html and\n"
             "     web/site/crosstab.partial.html. Edit those and re-run tradecraft/web/build-demo.py.\n"
             "     Editing this file directly means the hosted demo and the page stop agreeing,\n"
             "     which is the whole defect this capstone was filed for. -->")


def read(path):
    if not os.path.isfile(path):
        sys.exit("missing %s" % os.path.relpath(path, SERIES))
    return io.open(path, encoding="utf-8").read()


def render():
    """Return {absolute_path: content} for the three site files. Pure."""
    tpl = read(TEMPLATE)
    main = re.search(r"<main>\n(.*?)\n</main>", tpl, re.DOTALL)
    if not main:
        sys.exit("no <main> in demo.template.html -- the splitter's assumption about its shape is stale")
    body = "  <div class=\"tc-app\">\n%s\n  </div>" % main.group(1).rstrip()

    css = read(CSS).rstrip("\n") + "\n\n" + read(SITE_CSS).rstrip("\n") + "\n"
    js = read(UI).rstrip("\n") + "\n"

    layout = "\n".join([
        "{{ define \"main\" }}",
        GENERATED,
        "<link rel=\"stylesheet\" href=\"/tech/_kit/tech-kit.css\">",
        "<link rel=\"stylesheet\" href=\"/tech/tradecraft/tradecraft.css\">",
        "",
        "<article class=\"content\">",
        "  <header class=\"tk-head\">",
        "    <span class=\"tk-eyebrow\"><span class=\"tk-led\"></span> evilrobots.lol / tech</span>",
        "    <h1 class=\"tk-title\">{{ .Title }}</h1>",
        "    {{ with .Params.description }}<p class=\"tk-sub\">{{ . }}</p>{{ end }}",
        "    <div class=\"tk-rule\"></div>",
        "  </header>",
        "",
        body,
        "",
        "  {{ .Content }}",
        "",
        read(SITE_PARTIAL).rstrip("\n"),
        "</article>",
        "",
        "{{/* engine.js FIRST: tradecraft.js grades nothing and calls window.Instrument. */}}",
        "<script src=\"/tech/instrument/engine.js\"></script>",
        "<script src=\"/tech/tradecraft/tradecraft.js\"></script>",
        "{{ end }}",
        "",
    ])
    return {
        os.path.join(STATIC, "tradecraft.css"): css,
        os.path.join(STATIC, "tradecraft.js"): js,
        LAYOUT: layout,
    }


def write(files):
    for path, content in sorted(files.items()):
        d = os.path.dirname(path)
        if not os.path.isdir(d):
            os.makedirs(d)
        io.open(path, "w", encoding="utf-8", newline="\n").write(content)
        print("wrote %s (%d bytes)" % (os.path.relpath(path, SERIES), len(content)))


def main():
    write(render())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
